# 5.3 Diagonalization

First, we import the numpy package and the linear algebra functions within numpy.

In [1]:
import numpy as np
from numpy import linalg as LA

To define a matrix, we use np.array and put the matrix within parentheses. The syntax for the matrix is to use square brackets to bookend the matrix, square brackets to bookend each row, and commas to separate individual entries and rows.

In [2]:
A = np.array([[5,8,-4],[8,5,-4],[-4,-4,-1]])
print(A)

[[ 5  8 -4]
 [ 8  5 -4]
 [-4 -4 -1]]


## Eigenstuff
To compute eigenvalues and corresponding eigenvectors, we use the LA.eig command. Its output is a vector consisting of the eigenvalues (which we will name w) and a matrix consisting of an eigenvector basis (which we will name P). 

In [3]:
w, P = LA.eig(A)

In [4]:
print(w)

[-3. 15. -3.]


In [5]:
print(P)

[[-0.74535599  0.66666667 -0.03368509]
 [ 0.59628479  0.66666667  0.47370474]
 [-0.2981424  -0.33333333  0.88003928]]


We can also compute the determinant using the LA.det command. We see that as we recall, the determinant is the product of the eignevalues.

In [6]:
LA.det(A)

135.00000000000003

## Diagonalization
We will create a new matrix D which is a diagonal matrix with the eigenvalues of c along the diagonal. We then verify that $PDP^{-1}$ is equal to our original matrix c. 
 - To create a diagonal matrix we use the np.diagflat command.
 - To multiply matrices we can use the @ symbol
 - To compute an inverse we can use the LA.inv command

In [7]:
D = np.diagflat(w)
print(D)

[[-3.  0.  0.]
 [ 0. 15.  0.]
 [ 0.  0. -3.]]


In [8]:
P @ D @ LA.inv(P)

array([[ 5.,  8., -4.],
       [ 8.,  5., -4.],
       [-4., -4., -1.]])

## Problems for you to try
Are the matrices $$\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} \text{ and } \begin{bmatrix} 2 & 4 & 3 \\ -4 & -6 & -3 \\ 3 & 3 & 1 \end{bmatrix}$$ diagonalizable?

In [9]:
B = np.array([[1,2],[3,4]])
C = np.array([[2,4,3],[-4,-6,-3],[3,3,1]])

In [10]:
l, Q = LA.eig(B)

In [11]:
print(l)

[-0.37228132  5.37228132]


In [12]:
print(Q)

[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [13]:
m, R = LA.eig(C)

In [14]:
print(m)

[ 1.+0.00000000e+00j -2.+4.43741475e-08j -2.-4.43741475e-08j]


In [15]:
print(R)

[[ 5.77350269e-01+0.00000000e+00j  7.07106781e-01+3.13772606e-08j
   7.07106781e-01-3.13772606e-08j]
 [-5.77350269e-01+0.00000000e+00j -7.07106781e-01+0.00000000e+00j
  -7.07106781e-01-0.00000000e+00j]
 [ 5.77350269e-01+0.00000000e+00j  2.21670630e-15-3.13772606e-08j
   2.21670630e-15+3.13772606e-08j]]


In [16]:
R @ np.diagflat(m) @  LA.inv(R)

array([[ 2.+2.64785493e-09j,  4.+6.26348292e-09j,  3.-1.49027072e-24j],
       [-4.-4.89168448e-09j, -6.-4.78202217e-09j, -3.+1.00783883e-24j],
       [ 3.+1.86264515e-09j,  3.+1.86264515e-09j,  1.-3.42072075e-25j]])