# 6.1 Dot Product, Length, & Orthogonality

First, we import the numpy package and the linear algebra functions within numpy.

In [1]:
import numpy as np
from numpy import linalg as LA

To define our vectors, we use np arrays.

In [2]:
a = np.array([1,2,3])
b = np.array([2,4,-3])
print(a,b)

[1 2 3] [ 2  4 -3]


## Dot Product
To compute the dot product of the vectors a and b defined above, we use the np.dot command.

In [3]:
np.dot(a,b)

1

## Length
There are several ways to compute the length (norm) of a vector. We can use 
 - The built in norm function LA.norm
 - The square root of the dot product of a vector with itself
 - The square root of the sum of the squares of the components

In [4]:
LA.norm(a)

3.7416573867739413

In [5]:
np.dot(a,a)**0.5

3.7416573867739413

In [6]:
(1**2+2**2+3**2)**0.5

3.7416573867739413

## Orthogonality
Are the vectors a & b above orthogonal? No, as we have already seen that their dot product is zero.

In [7]:
c = np.array([2,2,-2])

In [8]:
np.dot(a,c)

0

Since a & c have dot product zero, they are orthogonal.

## Problems for you
1. Compute the length of $\vec{w} = \begin{bmatrix} 2 \\ -6 \\ -9 \end{bmatrix}$
2. If $\vec{v} = \begin{bmatrix} 6 \\ 2 \\ -3 \end{bmatrix}$, compute the distance between $\vec v$ and $\vec w$.
3. Are $\vec{v}$ and $\vec w$ orthogonal?

In [9]:
a-b

array([-1, -2,  6])

In [10]:
a+3

array([4, 5, 6])

In [11]:
w = np.array([2,-6,-9])

In [12]:
v = np.array([6,2,-3])

In [13]:
LA.norm(v-w)

10.770329614269007

In [14]:
LA.norm(w-v)

10.770329614269007

In [15]:
np.dot(v,w)

27