# 6.4 Gram-Schmidt

First, we import the numpy package and the linear algebra functions within numpy.

In [1]:
import numpy as np
from numpy import linalg as LA

Merge your basis vectors $\vec x_1,\ldots,\vec x_p$ into a matrix $X$.

In [2]:
X = np.array([[-1.,1,1],[0,1,-1],[1,0,1]])
print(X)

[[-1.  1.  1.]
 [ 0.  1. -1.]
 [ 1.  0.  1.]]


Apply the Gram-Schmidt process to your vectors and output in a new matrix U.

In [3]:
def gramschmidt(V):    
    U = V.copy()
    for x in range (1,np.size(V,1)):
        for y in range (0,x):
            U[:,x] = U[:,x]-(np.dot(V[:,x],U[:,y])/np.dot(U[:,y],U[:,y]))*U[:,y]

    return U    
     

In [4]:
A = gramschmidt(X)

In [5]:
np.around(np.transpose(gramschmidt(X)) @ gramschmidt(X),2)

array([[2. , 0. , 0. ],
       [0. , 1.5, 0. ],
       [0. , 0. , 3. ]])

In [6]:
print(A)

[[-1.   0.5  1. ]
 [ 0.   1.  -1. ]
 [ 1.   0.5  1. ]]
