# 7.1 Symmetric Matrices

First, we import the numpy package and the linear algebra functions within numpy.

In [1]:
import numpy as np
from numpy import linalg as LA

To define a matrix, we use np.array and put the matrix within parentheses. The syntax for the matrix is to use square brackets to bookend the matrix, square brackets to bookend each row, and commas to separate individual entries and rows.

In [2]:
A = np.array([[1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1]])
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


## Eigenstuff
To compute eigenvalues and corresponding eigenvectors, we use the LA.eig command. Its output is a vector consisting of the eigenvalues (which we will name w) and a matrix consisting of an eigenvector basis (which we will name P). 

In [3]:
w, P = LA.eig(A)

In [4]:
print(w)

[0.00000000e+00 4.00000000e+00 0.00000000e+00 2.80731443e-32]


In [5]:
print(np.around(P,3))

[[-0.866 -0.5   -0.866 -0.646]
 [ 0.289 -0.5    0.289 -0.328]
 [ 0.289 -0.5    0.289  0.487]
 [ 0.289 -0.5    0.289  0.487]]


Note that this eigenvector basis is orthonormal. (The "normal" part of it is a feature of Python, but it should be orthogonal nonetheless)

In [6]:
np.around(np.transpose(P) @ P)

array([[1., 0., 1., 1.],
       [0., 1., 0., 0.],
       [1., 0., 1., 1.],
       [1., 0., 1., 1.]])

## Diagonalization
We will create a new matrix D which is a diagonal matrix with the eigenvalues of c along the diagonal. We then verify that $PDP^{-1}$ is equal to our original matrix c. 
 - To create a diagonal matrix we use the np.diagflat command.
 - To multiply matrices we can use the @ symbol
 - To compute an inverse we can use the LA.inv command

In [7]:
D = np.diagflat(w)
print(D)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 4.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 2.80731443e-32]]


In [8]:
P @ D @ LA.inv(P)

LinAlgError: Singular matrix