# 6.5/6.6 Least-Squares

First, we import the numpy package and the linear algebra functions within numpy.

In [1]:
import numpy as np
from numpy import linalg as LA

Define $A$ and $\vec b$ for the equation $A\vec x=\vec b$ that you would like to solve.

In [16]:
A = np.array([[1,2],[-1,4],[1,2]])
b = np.array([[3],[-1],[5]])
print(A)
print(b)

[[ 1  2]
 [-1  4]
 [ 1  2]]
[[ 3]
 [-1]
 [ 5]]


Check to see if $A^T A$ is invertible.

In [17]:
LA.det(np.transpose(A) @ A)

72.0

If it is invertible, we can compute this easily using the inverse of $A^TA$

In [18]:
LA.inv(np.transpose(A) @ A)@np.transpose(A) @ b

array([[3. ],
       [0.5]])

In [19]:
np.transpose(A) @ b

array([[ 9],
       [12]])