# 6.2 Orthogonal Sets

First, we import the numpy package and the linear algebra functions within numpy.

In [1]:
import numpy as np
from numpy import linalg as LA

In [7]:
a = np.array([[1],[2],[3]])
b = np.array([[3],[0],[-1]])
c = np.array([[-1],[5],[-3]])

We append the vectors together using the np.concatenate function.

In [17]:
A = np.concatenate((a,b,c),axis=1)
print(A)

[[ 1  3 -1]
 [ 2  0  5]
 [ 3 -1 -3]]


In [16]:
np.around(np.transpose(A) @ A, decimals=10)

array([[14,  0,  0],
       [ 0, 10,  0],
       [ 0,  0, 35]])